# Generated by Django 4.0.8 on 2022-11-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0004_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
