# Generated by Django 4.0.8 on 2022-11-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0009_rename_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
