# Generated by Django 4.0.8 on 2022-11-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0010_account_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='point',
            new_name='points',
        ),
    ]
